spring.application.name=Trello

# Базовый URL для H2
spring.datasource.url=jdbc:h2:file:./data/mydb;DB_CLOSE_DELAY=-1

# Учетные данные для доступа
spring.datasource.username=sa
spring.datasource.password=password
spring.datasource.driver-class-name=org.h2.Driver

# Включение веб-консоли для просмотра таблиц (доступна по пути /h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Включение отображения SQL-запросов для отладки
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Отключаем стандартную Whitelabel Error Page
spring.web.error.whitelabel.enabled=false

# обработка 404 через исключения (для NoHandlerFoundException)
spring.web.resources.add-mappings=false

# Не показываем stack trace в продакшене
spring.web.error.include-stacktrace=never
spring.web.error.include-message=never